import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
    en:{
        driver: 'Driver',
        drivers: 'Drivers',
        none: 'None',
        firstName: 'First Name',
        lastName: 'First Name',
        email: 'Email',
        save: 'Save',
        create: 'Create',
        createEmployee: 'Create employee',
        createTask: 'Create task',
        createVehicle: 'Create vehicle',
        createGeofence: 'Create geofence',
        employees: 'Employees',
        role: 'Role',
        startChatWith: 'Start chat with...',
        password: 'Password',
        passwordConfirm: 'Confirm password',
        employeeName: 'Employee name',
        name: 'Name',
        number: 'Number',
        model: 'Model',
        productionYear: 'Production year',
        general: 'General',
        restrictions: 'Restrictions',
        enterRestricted: 'Enter restriction',
        leaveRestricted: 'Leave restriction',
        vehicles: 'Vehicles',
        vehicle: 'Vehicle',
        geofenceOrVehicle: 'Geofence or vehicle name',
        geofences: 'Geofences',
        description: 'Description',
        dueTime: 'Due datetime',
        typeHere: 'Type here...',
        attach: 'Attach',
        update: 'Update',
        send: 'Send',
        selectImage: 'Select image...',
        roleRestriction: 'Access only for the Administrators',
        tasksSearchPlaceholder: 'Task id, name or driver name',
        account: 'Account',
        newPassword: 'New password',
        newPasswordConfirm: 'Confirm new password',
        resetPassword: 'Reset password',
        companySettings: 'Company settings',
        landingPage: 'Landing Page',
        notifications: 'Notifications',
        notificationType: 'Notification type',
        generate: 'Generate',
        forgotPassword: 'Forgot Password?',
        passwordForget: 'Password Forget',
        reports: 'Reports',
        template: 'Template',
        signIn: 'Sign In',
        vehicleSearchPlaceholder: 'Vehicle name or driver name',
        tasks: 'Tasks',
        home: 'Home',
        taskboard: 'Taskboard',
        chat: 'Char',
        signOut: 'Sign Out',
        androidLocalFrequency: 'Android: frequency of data recording to local DB, ms',
        androidSyncFrequency: 'Android: frequency of data synchronization with Data processing service, ms',
        comments: 'Comments',
        vehicleName: 'Vehicle Name',
        workingHours: 'Working hours',
        datetime: 'Datetime',
        latitude: 'Latitude',
        longitude: 'Longitude',
        speed: 'Speed, km/h',
        fuelLevel: 'Fuel level, %',
        airFuelRatio: 'Air-fuel ratio',
        rpmEngine: 'Engine RPM',
        rpmEngineDescription: 'Engine Revolutions Per Minute',
        load: 'Engine load',
        absoluteLoad: 'Engine absolute load',
        engineCoolantTemperature: 'Engine coolant temperature',
        airIntakeTemperature: 'Air intake temperature',
        ambientAirTemperature: 'Ambient air temperature',
        distanceMilControl: 'Mileage',
        distanceSinceCcControl: 'Mileage since last drop',
        dtcNumber: 'Dtc number',
        pendingTroubleCodes: 'Engine pending trouble codes',
        permanentTroubleCodes: 'Engine permanent trouble codes',
        troubleCodes: 'Engine trouble codes',
        all: 'All',
    },
    ru: {
        driver: 'Водитель',
        drivers: 'Водители',
        none: 'Нету',
        firstName: 'Имя',
        lastName: 'Фамилия',
        email: 'Электронная почта',
        save: 'Сохранить',
        create: 'Создать',
        createEmployee: 'Создать сотрудника',
        createTask: 'Создать задачу',
        createVehicle: 'Создать автомобиль',
        createGeofence: 'Создать геозону',
        employees: 'Сотрудники',
        role: 'Роль',
        startChatWith: 'Начать переписку с...',
        password: 'Пароль',
        passwordConfirm: 'Подтвердите пароль',
        employeeName: 'Имя сотрудника',
        name: 'Название',
        number: 'Номер',
        model: 'Модель',
        productionYear: 'Год производства',
        general: 'Общие',
        restrictions: 'Ограничения',
        enterRestricted: 'Ограничение въезда',
        leaveRestricted: 'Ограничение выезда',
        vehicles: 'Транспортные средства',
        vehicle: 'Транспортное средство',
        geofenceOrVehicle: 'Имя геозоны или автомобиля',
        geofences: 'Геозоны',
        description: 'Описание',
        dueTime: 'Срок исполнения',
        typeHere: 'Печатайте...',
        attach: 'Прикрепить',
        update: 'Обновить',
        send: 'Отправить',
        selectImage: 'Выберите изображение...',
        roleRestriction: 'Доступно только для Администраторов',
        tasksSearchPlaceholder: 'Имя,номер задачи или имя водителя',
        account: 'Аккаунт',
        newPassword: 'Новый пароль',
        newPasswordConfirm: 'Подтвердите новый пароль',
        resetPassword: 'Изменить пароль',
        companySettings: 'Настройки компании',
        landingPage: 'Целевая страница',
        notifications: 'Уведомления',
        notificationType: 'Тип уведомления',
        generate: 'Сформировать',
        forgotPassword: 'Забыли пароль?',
        passwordForget: 'Восстановление пароля',
        reports: 'Отчеты',
        template: 'Тип отчета',
        signIn: 'Войти',
        vehicleSearchPlaceholder: 'Название авто, имя водителя',
        tasks: 'Задачи',
        home: 'Главная',
        taskboard: 'Доска задач',
        chat: 'Чат',
        signOut: 'Выйти',
        androidLocalFrequency: 'Андроид: частота записи данных в локальную БД, мс',
        androidSyncFrequency: 'Андроид: частота синхронизации данных с сервером, мс',
        comments: 'Комментарии',
        vehicleName: 'Название автомобиля',
        workingHours: 'Количество отработанных часов',
        datetime: 'Время и дата',
        latitude: 'Широта',
        longitude: 'Долгота',
        speed: 'Скорость, км/ч',
        fuelLevel: 'Уровень топлива, %',
        airFuelRatio: 'Отношение воздух-топливо',
        rpmEngine: 'Обороты двигателя',
        rpmEngineDescription: 'Обороты двигателя в минуту',
        load: 'Загрузка двигателя',
        absoluteLoad: 'Абсолютная загрузка двигателя',
        engineCoolantTemperature: 'Температура охлаждаемой жидкости',
        airIntakeTemperature: 'Температура вбираемого воздуха',
        ambientAirTemperature: 'Температура воздуха за бортом',
        distanceMilControl: 'Проблег',
        distanceSinceCcControl: 'Пробег с последнего сброса',
        dtcNumber: 'Количество ошибок двигателя',
        pendingTroubleCodes: 'Коды переменных ошибок двигателя',
        permanentTroubleCodes: 'Коды постоянных ошибок двигателя',
        troubleCodes: 'Коды ошибок двигателя',
        all: 'Все',
    }
});

export default strings;
